# Site settings
title: VALUE Project
email: vitor.freitas@oulu.fi
description: > # The main goal of the VALUE project is to provide a mechanism 
  for companies to forecast the overall value associated with a decision 
  relating to software/product management and development.

baseurl: ""
url: "http://valueproject.fi"

markdown: kramdown
